modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lootexplorer"
version = "${version}"
displayName = "LootExplorer"
displayTest = "IGNORE_ALL_VERSION"
authors = "VgLevelUp"
description = '''

'''
${neoforge_icon_field} = "icon.png"

[[dependencies.lootexplorer]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lootexplorer]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lootexplorer]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.lootexplorer]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "NONE"
side = "CLIENT"

[features.lootexplorer]
javaVersion = "[${java_version},)"

[[mixins]]
config = "lootexplorer.mixins.json"
