modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lootexplorer"
version = "${version}"
displayName = "LootExplorer"
authors = "VgLevelUp"
description = '''

'''
#logoFile = ""

[[dependencies.lootexplorer]]
modId = "neoforge"
type = "required"
versionRange = "[26,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lootexplorer]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lootexplorer]]
modId = "architectury"
type = "required"
versionRange = "[20.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "lootexplorer.mixins.json"
